export const RUNTIME_FALLBACK_RETRYABLE_ERROR_PATTERNS = [
  /rate.?limit/i,
  /too.?many.?requests/i,
  /quota\s+will\s+reset\s+after/i,
  /quota.?exceeded/i,
  /exceeded.*quota/i,
  /usage\s*quota/i,
  /free.?usage/i,
  /usage.?exceeded/i,
  /exhausted\s+your\s+capacity/i,
  /limit\s+exhausted/i,
  /all\s+credentials\s+for\s+model/i,
  /^Claude Code returned an error result: You've hit your (?:session )?limit\s+·\s+resets\s+\d{1,2}(?::\d{2})?(?:am|pm)\b/im,
  /^All [1-9]\d* account\(s\) failed \(server errors or auth issues\)\. Check account health with `codex-health`\.$/i,
  /Meridian['’]s session bookkeeping is saturated/i,
  /shared session mapping changed before publication/i,
  /cool(?:ing)?\s+down/i,
  /model.{0,20}?not.{0,10}?supported/i,
  /model_not_supported/i,
  /service.?unavailable/i,
  /overloaded/i,
  /temporarily.?unavailable/i,
  /try.?again/i,
  /(?:^|\s)429(?:\s|$)/,
  /(?:^|\s)503(?:\s|$)/,
  /(?:^|\s)529(?:\s|$)/,
  /使用上限/,
  /频率限制/,
  /请求过于频繁/,
  /暂时不可用/,
  /服务不可用/,
  /请稍后重试/,
] as const
